global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using SentIt.Commands;
global using SentIt.Globals;
global using SentIt.Interfaces;
global using System.Windows;
global using SentIt.Models;
global using System.Collections.ObjectModel;
global using System.Windows.Controls;
global using System.Windows.Forms;
global using System.Windows.Input;
global using System.ComponentModel;
global using System.Runtime.CompilerServices;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using SentIt.Navigation;
global using SentIt.ViewModels;
global using Application = System.Windows.Application;
global using UserControl = System.Windows.Controls.UserControl;